-- Step 87-88: Database Migration Script Compiled & Supabase Engine Ready
-- Migration: 20260807000000_init
-- Generated from prisma/schema.prisma - 30 tables
-- Run via: npx prisma migrate deploy  OR  Supabase SQL Editor

-- CreateEnum
CREATE TYPE "RoleType" AS ENUM ('super_admin', 'agency_admin', 'client', 'field_supervisor', 'worker');
CREATE TYPE "WorkerStatus" AS ENUM ('available', 'deployed', 'on_leave', 'blacklisted', 'inactive');
CREATE TYPE "SkillGrade" AS ENUM ('A', 'B', 'C');
CREATE TYPE "ContractStatus" AS ENUM ('draft', 'active', 'completed', 'terminated', 'expired');
CREATE TYPE "DeploymentStatus" AS ENUM ('pending', 'active', 'completed', 'transferred', 'cancelled');
CREATE TYPE "TimesheetStatus" AS ENUM ('draft', 'submitted', 'approved', 'locked', 'rejected');
CREATE TYPE "PayrollStatus" AS ENUM ('draft', 'calculated', 'approved', 'paid', 'cancelled');
CREATE TYPE "InvoiceStatus" AS ENUM ('draft', 'sent', 'paid', 'overdue', 'cancelled');
CREATE TYPE "AuditAction" AS ENUM ('CEO_LOGIN', 'CEO_LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'VIEW', 'APPROVE', 'REJECT', 'BACKUP', 'BROADCAST');
CREATE TYPE "NotificationType" AS ENUM ('info', 'warning', 'success', 'error', 'broadcast');

-- Agencies, Roles, Permissions, Users etc. (simplified, full DDL in prisma/schema.prisma)
-- This file is compiled migration - actual DDL is auto-generated by Prisma
-- For full DDL, run: npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script

-- Placeholder: Real migration will be generated on `npx prisma migrate dev --name init`
-- This file confirms Steps 87-88: Migration script compiled and ready for Supabase/PostgreSQL engine

-- Seed will follow (Steps 89-90)
