/**
 * Step 269: Auto-Generated Weekly Summary Email
 */

export interface WeeklySummary {
  week: string;
  totalWorkers: number;
  deployed: number;
  idle: number;
  totalTimesheets: number;
  totalPayroll: number;
  overdueInvoices: number;
}

export function generateWeeklySummaryEmail(summary: WeeklySummary): { subject: string; html: string } {
  const subject = `Weekly Summary: ${summary.week} - iNAYATechLab Manpower`;
  const html = `
  <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #1D0B2E; padding: 24px;">
    <div style="background: #1D0B2E; color: white; padding: 16px; text-align: center;">
      <h1 style="color: #E5B84B; margin:0;">Weekly Summary</h1>
      <p style="color: #B388FF; margin:0;">${summary.week}</p>
    </div>
    <table style="width:100%; margin-top: 16px; font-size: 14px;">
      <tr><td>Total Workers</td><td style="text-align:right; font-weight:bold;">${summary.totalWorkers}</td></tr>
      <tr><td>Deployed</td><td style="text-align:right; color: #B388FF;">${summary.deployed}</td></tr>
      <tr><td>Idle</td><td style="text-align:right; color: #E5B84B;">${summary.idle}</td></tr>
      <tr><td>Timesheets</td><td style="text-align:right;">${summary.totalTimesheets}</td></tr>
      <tr><td>Payroll</td><td style="text-align:right;">$${summary.totalPayroll}</td></tr>
      <tr><td>Overdue Invoices</td><td style="text-align:right; color: #EF4444;">${summary.overdueInvoices}</td></tr>
    </table>
    <p style="text-align:center; font-size: 12px; color: #999; margin-top: 16px;">Auto-generated by iNAYATechLab Manpower SaaS v2.1.0</p>
  </div>
  `;
  return { subject, html };
}
